import { createFileRoute, Link } from '@tanstack/react-router'
import { ArrowRight } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { CategoryCard, LessonCard, SiteLayout, TestimonialCard } from '@/components/site'
import { categories, lessons } from '@/lib/mock-data'
import professor from '@/assets/professor.jpg'

export const Route = createFileRoute('/')({ head: () => ({ meta: [{ title:'Matris — Matemática simples, clara e objetiva' },{ name:'description',content:'Aulas gravadas de Matemática do Fundamental aos concursos militares.'},{ property:'og:title',content:'Matris — Matemática simples, clara e objetiva'},{ property:'og:description',content:'Estude Matemática no seu ritmo com aulas organizadas e objetivas.'},{ property:'og:type',content:'website'},{ name:'twitter:card',content:'summary_large_image'}] }), component: Home })
function Home(){return <SiteLayout>
<section className="relative mx-auto grid max-w-7xl items-center gap-10 px-5 py-14 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:py-24"><div><span className="inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-1 font-mono text-[11px] uppercase tracking-[.16em] text-muted-foreground"><i className="size-1.5 rounded-full bg-primary"/>Matemática, do Fundamental ao IME</span><h1 className="mt-6 max-w-3xl font-display text-5xl font-semibold leading-[1.04] sm:text-6xl">Aprenda Matemática de forma <em className="text-primary">simples</em>, clara e objetiva.</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-muted-foreground">Aulas gravadas para você estudar no seu ritmo, revisar quando quiser e evoluir de verdade.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg" className="rounded-full"><Link to="/aulas">Ver as aulas <ArrowRight/></Link></Button><Button asChild variant="outline" size="lg" className="rounded-full"><Link to="/sobre">Conhecer o professor</Link></Button></div><div className="mt-10 grid max-w-xl grid-cols-3 gap-3 font-mono text-[10px] text-muted-foreground sm:text-xs"><span><b className="block text-sm text-foreground">320+</b>aulas gravadas</span><span><b className="block text-sm text-foreground">9</b>concursos militares</span><span><b className="block text-sm text-foreground">4,8</b>avaliação média</span></div></div><MathScene/></section>
<section className="mx-auto max-w-7xl px-5 py-10 sm:px-6"><div className="mb-6 flex items-end justify-between"><h2 className="font-display text-3xl font-semibold">Escolha sua trilha</h2><span className="font-mono text-xs text-muted-foreground">05 níveis de ensino</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.map((c,i)=><CategoryCard key={c.slug} category={c} index={i}/>)}</div></section>
<section className="mx-auto max-w-7xl px-5 py-10 sm:px-6"><div className="mb-6 flex items-end justify-between"><h2 className="font-display text-3xl font-semibold">Continue seus estudos</h2><Link to="/aulas" className="text-sm text-primary">Ver todas →</Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{lessons.slice(0,3).map(l=><LessonCard key={l.id} lesson={l}/>)}</div></section>
<section className="mx-auto max-w-7xl px-5 py-10 sm:px-6"><div className="overflow-hidden rounded-lg border border-border bg-card"><div className="grid items-center lg:grid-cols-[.42fr_1fr]"><img src={professor} alt="Retrato provisório do professor André Matos" loading="lazy" width={800} height={1008} className="h-full max-h-[420px] w-full object-cover"/><div className="p-7 lg:p-12"><p className="font-mono text-xs uppercase tracking-[.16em] text-primary">Sobre o professor</p><h2 className="mt-2 font-display text-4xl font-semibold">Prof. André Matos</h2><p className="mt-4 max-w-2xl leading-relaxed text-muted-foreground">Doutor em Matemática Aplicada, com 15 anos de sala de aula. Este texto e a imagem são demonstrativos e serão substituídos na versão final. Aulas pensadas para quem precisa de clareza, não de volume.</p><Button asChild variant="outline" className="mt-6 rounded-full"><Link to="/sobre">Conhecer trajetória</Link></Button></div></div></div></section>
<section className="mx-auto max-w-7xl px-5 py-10 sm:px-6"><h2 className="mb-6 font-display text-3xl font-semibold">O que meus alunos dizem</h2><div className="grid gap-4 lg:grid-cols-3"><TestimonialCard initials="LC" name="Larissa C." detail="Candidata IME">As aulas de análise combinatória mudaram minha nota. Finalmente entendi o porquê de cada passo.</TestimonialCard><TestimonialCard initials="RT" name="Rafael T." detail="Concurseiro AFA">Estudo no ônibus a caminho do trabalho. O ritmo é perfeito e a busca por assunto é rápida.</TestimonialCard><TestimonialCard initials="MF" name="Marina F." detail="Ensino Médio">Voltei a estudar depois de anos. O progresso semanal me mantém motivada.</TestimonialCard></div><p className="mt-3 font-mono text-[10px] text-muted-foreground">Depoimentos demonstrativos, substituíveis na versão final.</p></section>
</SiteLayout>}
function MathScene(){return <div className="relative h-[360px] sm:h-[440px]"><div className="math-glow absolute left-1/2 top-1/2 size-72 rounded-full bg-primary/30 blur-3xl sm:size-96"/><div className="absolute inset-0 rounded-lg border border-border bg-gradient-to-br from-cyan/10 via-transparent to-primary/10"/><svg viewBox="0 0 400 400" className="absolute inset-0 m-auto size-[280px] text-primary/50" fill="none" stroke="currentColor" strokeWidth="1"><circle cx="200" cy="200" r="150"/><circle className="math-draw" cx="200" cy="200" r="150" strokeDasharray="942" strokeDashoffset="942"/><path d="M200 50 L330 275 L70 275 Z"/><line x1="200" y1="50" x2="200" y2="350"/></svg><span className="absolute left-5 top-7 rounded-lg border border-border bg-background/70 px-4 py-3 font-mono text-sm backdrop-blur">a² + b² = c²</span><span className="absolute bottom-8 right-5 rounded-lg border border-border bg-background/70 px-4 py-3 font-mono text-sm backdrop-blur">∫ eˣ dx = eˣ + C</span></div>}
