import { Link, useParams } from '@tanstack/react-router'
import { Check, Clock3, MessageCircle, Pause, Play, Search, Star, Trophy } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { ExamCard, LessonCard, PageHeader, ProgressBar, Rating, SiteLayout } from '@/components/site'
import { categories, exams, lessons } from '@/lib/mock-data'
import professor from '@/assets/professor.jpg'

export function CategoryPage({ slug }: { slug: string }) { const category=categories.find(c=>c.slug===slug) ?? categories[0]; return <SiteLayout><PageHeader eyebrow="Trilha de estudos" title={category.name} description={category.detail}/><section className="mx-auto max-w-7xl px-5 sm:px-6"><div className="mb-8 grid gap-3 sm:grid-cols-3"><Stat value={category.count.split(' · ')[0]} label="conteúdo disponível"/><Stat value="12 semanas" label="trilha sugerida"/><Stat value="4,8" label="avaliação dos alunos"/></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{lessons.map(l=><LessonCard key={l.id} lesson={{...l,category:category.name}}/>)}</div></section></SiteLayout> }
export function LessonsPage(){return <SiteLayout><PageHeader eyebrow="Biblioteca" title="Todas as aulas" description="Encontre uma explicação objetiva por assunto, matéria ou nível de ensino."/><section className="mx-auto max-w-7xl px-5 sm:px-6"><div className="grid gap-3 rounded-lg border border-border bg-card p-4 sm:grid-cols-[1fr_auto]"><Input placeholder="Buscar por aula, assunto ou matéria" className="h-11"/><Button className="h-11 rounded-full"><Search/>Pesquisar</Button></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{lessons.map(l=><LessonCard key={l.id} lesson={l}/>)}</div></section></SiteLayout>}
export function SearchPage(){const[q,setQ]=useState('');const filtered=useMemo(()=>lessons.filter(l=>`${l.title} ${l.subject} ${l.category}`.toLowerCase().includes(q.toLowerCase())),[q]);return <SiteLayout><PageHeader eyebrow="Pesquisa global" title="O que você quer aprender?" description="Pesquise pelo nome da aula, assunto ou matéria."/><section className="mx-auto max-w-7xl px-5 sm:px-6"><div className="relative"><Search className="absolute left-4 top-1/2 size-5 -translate-y-1/2 text-muted-foreground"/><Input value={q} onChange={e=>setQ(e.target.value)} autoFocus placeholder="Ex.: equações, trigonometria, álgebra…" className="h-14 rounded-full bg-card pl-12 text-base"/></div><p className="my-6 font-mono text-xs text-muted-foreground">{filtered.length} resultados encontrados</p><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(l=><LessonCard key={l.id} lesson={l}/>)}</div></section></SiteLayout>}
export function ExamsPage(){return <SiteLayout><PageHeader eyebrow="Preparação por edital" title="Concursos Militares" description="Trilhas demonstrativas organizadas para cada prova, fáceis de atualizar quando disciplinas e editais mudarem."/><section className="mx-auto grid max-w-7xl gap-4 px-5 sm:grid-cols-2 sm:px-6 lg:grid-cols-3">{exams.map(e=><ExamCard key={e.slug} exam={e}/>)}</section></SiteLayout>}
export function ExamDetailPage(){const {slug}=useParams({strict:false}) as {slug?:string}; const exam=exams.find(e=>e.slug===slug)??exams[1]; const subjects=exam.slug==='espcex'?['Matemática','Português','Física','História','Geografia','Inglês']:['Matemática','Português','Física','Inglês','Conhecimentos gerais']; return <SiteLayout><PageHeader eyebrow="Concursos Militares" title={`Preparação para ${exam.name}`} description={exam.description}/><section className="mx-auto max-w-7xl px-5 sm:px-6"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div className="rounded-lg border border-border bg-card p-6"><Trophy className="size-8 text-amber"/><h2 className="mt-5 font-display text-2xl">Disciplinas</h2><div className="mt-4 space-y-2">{subjects.map((s,i)=><div key={s} className="flex items-center justify-between rounded-md bg-muted/60 px-4 py-3 text-sm"><span>{s}</span><span className="font-mono text-xs text-muted-foreground">{12+i*3} aulas</span></div>)}</div></div><div><h2 className="mb-4 font-display text-2xl">Aulas recomendadas</h2><div className="grid gap-4 sm:grid-cols-2">{lessons.slice(0,4).map(l=><LessonCard key={l.id} lesson={l}/>)}</div></div></div></section></SiteLayout>}
export function LessonPage(){const {id}=useParams({strict:false}) as {id?:string};const lesson=lessons.find(l=>l.id===id)??lessons[0];const[done,setDone]=useState(false);return <SiteLayout><PageHeader eyebrow={`${lesson.subject} · ${lesson.category}`} title={lesson.title} description={`Prof. André Matos · ${lesson.duration}`}/><section className="mx-auto grid max-w-7xl gap-8 px-5 sm:px-6 lg:grid-cols-[1fr_320px]"><div><div className="relative aspect-video overflow-hidden rounded-lg bg-foreground"><img src={lesson.image} alt="Capa da videoaula" width={1088} height={608} className="h-full w-full object-cover opacity-70"/><button className="absolute inset-0 m-auto grid size-20 place-items-center rounded-full bg-primary text-primary-foreground" aria-label="Reproduzir aula"><Play className="size-8" fill="currentColor"/></button><div className="absolute inset-x-5 bottom-5"><ProgressBar value={done?100:42}/></div></div><div className="mt-5 flex flex-wrap gap-2"><Button onClick={()=>setDone(!done)} className="rounded-full"><Check/>{done?'Concluída':'Marcar como concluída'}</Button><Button variant="outline" className="rounded-full"><Pause/>Parei na metade</Button><Button variant="outline" className="rounded-full"><MessageCircle/>Comentar</Button></div><h2 className="mt-10 font-display text-2xl">Sobre esta aula</h2><p className="mt-3 leading-relaxed text-muted-foreground">Nesta aula demonstrativa, você aprende os conceitos essenciais com uma sequência clara de exemplos e exercícios resolvidos. O conteúdo poderá ser atualizado pelo professor posteriormente.</p><Comments/></div><aside className="space-y-5"><div className="rounded-lg border border-border bg-card p-5"><p className="font-mono text-xs uppercase text-muted-foreground">Avaliação</p><div className="mt-3 flex items-end gap-3"><strong className="font-display text-5xl">4,8</strong><div><Rating value={5}/><p className="mt-1 text-xs text-muted-foreground">124 avaliações</p></div></div>{[5,4,3,2,1].map((n)=><div key={n} className="mt-3 grid grid-cols-[14px_1fr_30px] items-center gap-2 text-xs"><span>{n}</span><ProgressBar value={n===5?78:n===4?16:2}/><span className="text-muted-foreground">{n===5?'78%':n===4?'16%':'2%'}</span></div>)}</div><div><h2 className="mb-3 font-display text-xl">Próxima aula</h2><LessonCard lesson={lessons[1]}/></div></aside></section><section className="mx-auto max-w-7xl px-5 py-12 sm:px-6"><h2 className="mb-4 font-display text-2xl">Aulas relacionadas</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{lessons.slice(2,5).map(l=><LessonCard key={l.id} lesson={l}/>)}</div></section></SiteLayout>}
function Comments(){const[text,setText]=useState('');return <section className="mt-10"><h2 className="font-display text-2xl">Comentários e dúvidas</h2><div className="mt-4 rounded-lg border border-border bg-card p-4"><Textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Professor, poderia explicar novamente essa parte?" className="min-h-24"/><Button className="mt-3 rounded-full" onClick={()=>setText('')}>Enviar comentário</Button></div><div className="mt-4 space-y-3"><div className="rounded-lg border border-border p-4"><strong className="text-sm">Marina F.</strong><p className="mt-2 text-sm text-muted-foreground">Professor, poderia explicar novamente por que o sinal muda nesta etapa?</p><div className="ml-5 mt-3 border-l-2 border-primary pl-4"><span className="text-xs font-medium text-primary">Prof. André</span><p className="mt-1 text-sm text-muted-foreground">Claro! Isso acontece porque distribuímos o sinal negativo por todos os termos.</p></div></div></div></section>}
function Stat({value,label}:{value:string;label:string}){return <div className="rounded-lg border border-border bg-card p-5"><strong className="font-display text-3xl">{value}</strong><p className="mt-1 text-sm text-muted-foreground">{label}</p></div>}
